name: .NET Core

on:
  push:
    branches: [ main ]
    paths: './package/LibSassBuilder.nuspec'

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: dotnet publish
      run: dotnet publish -c Release -o ..\package\tool\ .\LibSassBuilder\
